/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import Login.MyCNX;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Menu_Form_Admin extends javax.swing.JFrame {

    private int UserID;

    /**
     * Creates new form Menu_Form
     */
    public Menu_Form_Admin() {
        initComponents();
    }

    public void setUserID(int userID) {
        this.UserID = userID;
    }

    public void getAdminProfileFromDatabase(String username) {
        //Set Fullname
        jTextField_Username.setText(username);
        jTextField_Username.setEditable(false);
        //Get the Data from each query
        PreparedStatement ps;
        ResultSet rs;
        try {
            String query = "select * from Users where Username =?";

            ps = MyCNX.getConnection().prepareStatement(query);
            ps.setString(1, username);
            rs = ps.executeQuery();

            if (rs.next()) {
                String Fullname = rs.getString("Fullname");
                String Job = rs.getString("Job");
                String Phone = rs.getString("Phone");
                String Address = rs.getString("Address");
                String Email = rs.getString("Email");
                jTextField_Fullname.setText(Fullname);
                jTextField_Fullname.setEditable(false);
                jTextField_Job.setText(Job);
                jTextField_Job.setEditable(false);
                jTextField_Phone.setText(Phone);
                jTextField_Phone.setEditable(false);
                jTextField_Email.setText(Email);
                jTextField_Email.setEditable(false);
                jTextField_Address.setText(Address);
                jTextField_Address.setEditable(false);

                UserID = rs.getInt("UserID");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void getUserListFromDatabase() {
        PreparedStatement ps;
        ResultSet rs;
        try {
            jTable_UserList.setModel(new DefaultTableModel(null, new Object[]{"ID", "Username", "Fullname", "Job", "Phone", "Address", "Email"}));
            String sql = "select * from Users where not UserID = ?";

            ps = MyCNX.getConnection().prepareStatement(sql);
            ps.setInt(1, UserID);
            rs = ps.executeQuery();

            while (rs.next()) {
                String id = String.valueOf(rs.getInt("UserID"));
                String Username = String.valueOf(rs.getString("Username"));
                String Fullname = String.valueOf(rs.getString("Fullname"));
                String Job = String.valueOf(rs.getString("Job"));
                String Phone = String.valueOf(rs.getString("Phone"));
                String Address = String.valueOf(rs.getString("Address"));
                String Email = String.valueOf(rs.getString("Email"));
                Object tbData[] = {id, Username, Fullname, Job, Phone, Address, Email};
                DefaultTableModel tblModel = (DefaultTableModel) jTable_UserList.getModel();
                tblModel.addRow(tbData);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        JPanel_AdminProfile = new javax.swing.JPanel();
        jLabel_AdminProfile = new javax.swing.JLabel();
        jButton_EditAdminProfile = new javax.swing.JButton();
        jButton_RefreshProfile = new javax.swing.JButton();
        jPanel_AdminInfo = new javax.swing.JPanel();
        jLabel_UserName = new javax.swing.JLabel();
        jLabel_Fullname = new javax.swing.JLabel();
        jLabel_Phone = new javax.swing.JLabel();
        jLabel_Job = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel_Address = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jTextField_Fullname = new javax.swing.JTextField();
        jTextField_Phone = new javax.swing.JTextField();
        jTextField_Job = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_Address = new javax.swing.JTextField();
        jPanel_UserList = new javax.swing.JPanel();
        jLabel_UserList = new javax.swing.JLabel();
        jButton_Add = new javax.swing.JButton();
        jButton_Refresh = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jScrollPane_UserListTable = new javax.swing.JScrollPane();
        jTable_UserList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(248, 148, 6));

        JPanel_AdminProfile.setBackground(new java.awt.Color(248, 148, 6));

        jLabel_AdminProfile.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel_AdminProfile.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_AdminProfile.setText("Admin Profile");

        jButton_EditAdminProfile.setText("Edit");
        jButton_EditAdminProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_EditAdminProfileMouseClicked(evt);
            }
        });

        jButton_RefreshProfile.setText("Refresh");
        jButton_RefreshProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_RefreshProfileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JPanel_AdminProfileLayout = new javax.swing.GroupLayout(JPanel_AdminProfile);
        JPanel_AdminProfile.setLayout(JPanel_AdminProfileLayout);
        JPanel_AdminProfileLayout.setHorizontalGroup(
            JPanel_AdminProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_AdminProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_AdminProfile)
                .addGap(129, 129, 129)
                .addComponent(jButton_RefreshProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_EditAdminProfile)
                .addContainerGap(666, Short.MAX_VALUE))
        );
        JPanel_AdminProfileLayout.setVerticalGroup(
            JPanel_AdminProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_AdminProfileLayout.createSequentialGroup()
                .addComponent(jLabel_AdminProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(JPanel_AdminProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanel_AdminProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_EditAdminProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_RefreshProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel_AdminInfo.setBackground(new java.awt.Color(44, 62, 80));

        jLabel_UserName.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_UserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_UserName.setText("Username");

        jLabel_Fullname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Fullname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Fullname.setText("Full Name");
        jLabel_Fullname.setMaximumSize(new java.awt.Dimension(53, 16));
        jLabel_Fullname.setMinimumSize(new java.awt.Dimension(53, 16));
        jLabel_Fullname.setPreferredSize(new java.awt.Dimension(53, 16));

        jLabel_Phone.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Phone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Phone.setText("Phone");

        jLabel_Job.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Job.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Job.setText("Job");

        jLabel_Email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Email.setText("Email");
        jLabel_Email.setMaximumSize(new java.awt.Dimension(53, 16));
        jLabel_Email.setMinimumSize(new java.awt.Dimension(53, 16));
        jLabel_Email.setPreferredSize(new java.awt.Dimension(53, 16));

        jLabel_Address.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Address.setText("Address");

        javax.swing.GroupLayout jPanel_AdminInfoLayout = new javax.swing.GroupLayout(jPanel_AdminInfo);
        jPanel_AdminInfo.setLayout(jPanel_AdminInfoLayout);
        jPanel_AdminInfoLayout.setHorizontalGroup(
            jPanel_AdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AdminInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_AdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel_AdminInfoLayout.createSequentialGroup()
                        .addComponent(jLabel_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Address))
                    .addGroup(jPanel_AdminInfoLayout.createSequentialGroup()
                        .addGroup(jPanel_AdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_Email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(jLabel_Fullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_UserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_AdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_AdminInfoLayout.createSequentialGroup()
                                .addGroup(jPanel_AdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_Fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_AdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel_AdminInfoLayout.createSequentialGroup()
                                        .addComponent(jLabel_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel_AdminInfoLayout.createSequentialGroup()
                                        .addComponent(jLabel_Job, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Job))))
                            .addComponent(jTextField_Email))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_AdminInfoLayout.setVerticalGroup(
            jPanel_AdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AdminInfoLayout.createSequentialGroup()
                .addGroup(jPanel_AdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_UserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_AdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Fullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Job, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_Job, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_AdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jTextField_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_AdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel_UserList.setBackground(new java.awt.Color(248, 148, 6));

        jLabel_UserList.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel_UserList.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_UserList.setText("User List");

        jButton_Add.setText("Add");
        jButton_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_AddMouseClicked(evt);
            }
        });

        jButton_Refresh.setText("Refresh");
        jButton_Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_RefreshMouseClicked(evt);
            }
        });

        jButton_Delete.setText("Delete");
        jButton_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_DeleteMouseClicked(evt);
            }
        });

        jButton_Update.setText("Update");
        jButton_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_UpdateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_UserListLayout = new javax.swing.GroupLayout(jPanel_UserList);
        jPanel_UserList.setLayout(jPanel_UserListLayout);
        jPanel_UserListLayout.setHorizontalGroup(
            jPanel_UserListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_UserListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_UserList, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jButton_Refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Update)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_UserListLayout.setVerticalGroup(
            jPanel_UserListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_UserListLayout.createSequentialGroup()
                .addComponent(jLabel_UserList, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_UserListLayout.createSequentialGroup()
                .addGroup(jPanel_UserListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Refresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTable_UserList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Fullname", "Job", "Phone", "Address", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane_UserListTable.setViewportView(jTable_UserList);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_UserList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane_UserListTable, javax.swing.GroupLayout.DEFAULT_SIZE, 1166, Short.MAX_VALUE)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JPanel_AdminProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_AdminInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(JPanel_AdminProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_AdminInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_UserList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_UserListTable, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_EditAdminProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_EditAdminProfileMouseClicked
        // TODO add your handling code here:
        Admin_Profile_Edit edit = new Admin_Profile_Edit();
        edit.setVisible(true);
        edit.pack();
        edit.getUsername(UserID);
        edit.getDataFromDatabase();
    }//GEN-LAST:event_jButton_EditAdminProfileMouseClicked

    private void jButton_RefreshProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RefreshProfileMouseClicked
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        try {
            String query = "select * from Users where UserID =?";

            ps = MyCNX.getConnection().prepareStatement(query);
            ps.setInt(1, UserID);
            rs = ps.executeQuery();

            if (rs.next()) {
                String Fullname = rs.getString("Fullname");
                String Job = rs.getString("Job");
                String Phone = rs.getString("Phone");
                String Address = rs.getString("Address");
                String Email = rs.getString("Email");
                jTextField_Fullname.setText(Fullname);
                jTextField_Fullname.setEditable(false);
                jTextField_Job.setText(Job);
                jTextField_Job.setEditable(false);
                jTextField_Phone.setText(Phone);
                jTextField_Phone.setEditable(false);
                jTextField_Email.setText(Email);
                jTextField_Email.setEditable(false);
                jTextField_Address.setText(Address);
                jTextField_Address.setEditable(false);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton_RefreshProfileMouseClicked

    private void jButton_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AddMouseClicked
        // TODO add your handling code here:
        Admin_Data_Add add = new Admin_Data_Add();
        add.setVisible(true);
        add.pack();
    }//GEN-LAST:event_jButton_AddMouseClicked

    private void jButton_RefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RefreshMouseClicked
        // TODO add your handling code here:
        getUserListFromDatabase();
    }//GEN-LAST:event_jButton_RefreshMouseClicked

    private void jButton_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DeleteMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) jTable_UserList.getModel();
        int getSelectedRowForDeletion = jTable_UserList.getSelectedRow();
        String deletedRows = jTable_UserList.getModel().getValueAt(getSelectedRowForDeletion, 0).toString();

        if (getSelectedRowForDeletion >= 0) {
            tblModel.removeRow(getSelectedRowForDeletion);
            PreparedStatement ps;

            try {
                String query = "delete from Users where UserID =" + deletedRows;

                ps = MyCNX.getConnection().prepareStatement(query);
                ps.execute();

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton_DeleteMouseClicked

    private void jButton_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_UpdateMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) jTable_UserList.getModel();
        if (tblModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Table is Empty");
        } else {
            for (int i = 0; i < tblModel.getRowCount(); i++) {
                Integer userId = Integer.valueOf(tblModel.getValueAt(i, 0).toString());
                System.out.println(userId);
                String username = tblModel.getValueAt(i, 1).toString();
                String fullname = tblModel.getValueAt(i, 2).toString();
                String job = tblModel.getValueAt(i, 3).toString();
                String phone = tblModel.getValueAt(i, 4).toString();
                String address = tblModel.getValueAt(i, 5).toString();
                String email = tblModel.getValueAt(i, 6).toString();

                String query = "update Users "
                        + "Set Username = ?, Fullname = ?, Job = ?, Phone = ?, Address = ?, Email = ? "
                        + "where UserID = ?";

                PreparedStatement ps;
                try {
                    ps = MyCNX.getConnection().prepareStatement(query);
                    ps.setString(1, username);
                    ps.setString(2, fullname);
                    ps.setString(3, job);
                    ps.setString(4, phone);
                    ps.setString(5, address);
                    ps.setString(6, email);
                    ps.setInt(7, userId);
                    ps.execute();
                } catch (SQLException ex) {
                    Logger.getLogger(Menu_Form_User.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton_UpdateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Form_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Form_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Form_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Form_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu_Form_Admin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel_AdminProfile;
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_EditAdminProfile;
    private javax.swing.JButton jButton_Refresh;
    private javax.swing.JButton jButton_RefreshProfile;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel_Address;
    private javax.swing.JLabel jLabel_AdminProfile;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Fullname;
    private javax.swing.JLabel jLabel_Job;
    private javax.swing.JLabel jLabel_Phone;
    private javax.swing.JLabel jLabel_UserList;
    private javax.swing.JLabel jLabel_UserName;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel_AdminInfo;
    private javax.swing.JPanel jPanel_UserList;
    private javax.swing.JScrollPane jScrollPane_UserListTable;
    private javax.swing.JTable jTable_UserList;
    private javax.swing.JTextField jTextField_Address;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Fullname;
    private javax.swing.JTextField jTextField_Job;
    private javax.swing.JTextField jTextField_Phone;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
